### ISSUE TITLE
Set up code tests

### ISSUE THREAD

**Issue by ezorita** [palicode/nucleotid-back#13]
## Description
Set up generic unit testing with `supertest`. 
## Subtasks
- [x] Install `supertest`
- [x] Docker-compose environment for test
- [x] Define `test` database
- [x] Initialize `test` database with dummy data
- [x] Define generic test structure
- [x] Write tests for all current API endpoints:
  - [x] `routes/user`
  - [x] `routes/auth`
- [x] Write unit tests for non-middleware function (sanitizers especially):
  - [x] `controllers/user/validateNewUser`
## Acceptance criteria
- [x] The testing strategy is modular and can be easily adapted to new code.
- [x]  Each test makes requests and checks HTTP status.
- [x] Test database failures?
- [ ] Test coverage ~100%
## References
http://willi.am/node-mocha-supertest/#1
## Dependencies
None.

**Comment by ezorita** [comment]
http://willi.am/node-mocha-supertest/#1
