### ISSUE TITLE
Set up code coverage

### ISSUE THREAD

**Issue by ezorita** [palicode/nucleotid-back#14]
## Description
Find a way to measure code coverage, integrate it with tests and send reports to coveralls.
## Subtasks
- [x] Find the way to measure coverage (Google V8, Istanbul...)
- [x] Integrate coverage in tests
- [x] Force test failure based on minimum coverage per file
- [x] Send reports to coveralls
## Acceptance criteria
- [x] Coverage reports are seamlessly integrated with tests.
- [x] Automatically sends coverage reports to coveralls.
## References
https://nodejs.org/api/cli.html#cli_node_v8_coverage_dir
https://docs.coveralls.io/javascript
https://github.com/nickmerwin/node-coveralls
## Dependencies
- Depends on #13
- Depends on #16

**Comment by ezorita** [comment]
https://docs.coveralls.io/javascript
https://github.com/nickmerwin/node-coveralls
