### ISSUE TITLE
User controller

### ISSUE THREAD

**Issue by ezorita** [palicode/nucleotid-back#15]
## Description
Complete the code that implements the user route logic.
## Subtasks
- [x] Require `validateCredentials` in critical operations like `updateUser` and `deleteUser`.
- [x] Use `nested transactions` for DB dependent data (`createWebUser`).
- [ ] Define sanitization parameters in `config.js`.
- Middlewares:
  - [x] `createWebUser`
  - [x] `validateEmail`
  - [x] `getUserProfile`
  - [x] `updateUser`
  - [x] `deleteUser`
  - [x] `validateCredentials`
- Middlewares (test code):
  - [x] `createWebUser`
  - [x] `validateEmail`
  - [x] `getUserProfile`
  - [x] `updateUser`
  - [x] `deleteUser`
  - [x] `validateCredentials`
- Functions:
  - [x] `parseUserData`

## Acceptance criteria
- [ ] Test code coverage ~100%.
- [x] Possibility to Create, Update, Read and Delete user information.
## Test procedures
- [x] Test user sanitizer with all options.
- [x] Test API endpoints.
## Dependencies
None.

**Comment by ezorita** [comment]
Nested transactions in pg-promise
https://github.com/vitaly-t/pg-promise/blob/master/examples/select-insert.md
