### ISSUE TITLE
Set up Continuous Integration

### ISSUE THREAD

**Issue by ezorita** [palicode/nucleotid-back#16]
## Description
Set up continuous integration. All test must be passed each time the code is pushed to the repository. Do not allow merging to branch `master` if CI fails.
## Subtasks
- [x] Set up Travis CI.
- [x] Configure yml file.
- [x] Use `docker-compose` in Travis.
## Acceptance criteria
- [x] The database must work in travis.
- [x] All tests must be performed correctly using the `test` environment on the CI server.
- [x] Merging to `master` is only possible through passing PRs.
## Dependencies
- Depends on #13
