### ISSUE TITLE
Team controller

### ISSUE THREAD

**Issue by ezorita** [palicode/nucleotid-back#20]
## Description
Code to read, create, delete and update Teams of users and their permissions.
## Subtasks
- Middlewares:
  - [ ] `createTeam`
  - [ ] `deleteTeam`
  - [ ] `updateTeam`
  - [ ] `getTeamUsers`
  - [ ] `addTeamUser`
  - [ ] `deleteTeamUser`
  - [ ] `updateTeamUser`
- Test code:
  - [ ] `createTeam`
  - [ ] `deleteTeam`
  - [ ] `updateTeam`
  - [ ] `addTeamUser`
  - [ ] `deleteTeamUser`
  - [ ] `updateTeamUser`
## Acceptance criteria
- [ ] Test code coverage ~100%.
- [ ] Possibility to Create, Read, Update and Delete a Team.
- [ ] Possibility to Create, Read, Update and Delete user permissions in a Team.
## Test procedures
- [ ] Test API endpoints.
- [ ] Test user permissions.
## Dependencies
Depends on #15
