### ISSUE TITLE
Notebook controller

### ISSUE THREAD

**Issue by ezorita** [palicode/nucleotid-back#21]
## Description
Code to read, create, delete and update Notebook metadata. This is just the metadata, i.e. the title of the notebook, the owner, the project it belongs to, and so on, but not the notebook data itself.
## Subtasks
- Middlewares:
  - [ ] `createNotebook`
  - [ ] `getNotebook`
  - [ ] `updateNotebook`
  - [ ] `deleteNotebook`
- Test code:
  - [ ] `createNotebook`
  - [ ] `getNotebook`
  - [ ] `updateNotebook`
  - [ ] `deleteNotebook`
## Acceptance criteria
- [ ] Test code coverage ~100%.
- [ ] Possibility to Create, Read, Update and Delete Notebooks.
## Test procedures
- [ ] Test API endpoints.
## Dependencies
Depends on #22
