### ISSUE TITLE
Project controller

### ISSUE THREAD

**Issue by ezorita** [palicode/nucleotid-back#22]
## Description
Code to read, create, delete and update Projects. It should be possible to transfer project ownership/team.
## Subtasks
- [ ] Solve ownership/team transfer problem.
- Middlewares:
  - [ ] `createProject`
  - [ ] `deleteProject`
  - [ ] `updateProject`
  - [ ] `getProject`
- Test code:
  - [ ] `createProject`
  - [ ] `deleteProject`
  - [ ] `updateProject`
  - [ ] `getProject`
## Acceptance criteria
- [ ] Test code coverage ~100%.
- [ ] Possibility to Create, Read, Update and Delete Projects.
## Test procedures
- [ ] Test API endpoints.
## Dependencies
Depends on #20
