### ISSUE TITLE
Notebook Data

### ISSUE THREAD

**Issue by ezorita** [palicode/nucleotid-back#24]
## Description
The data in notebook Steps
## Subtasks
- [ ] Define how to store notebook data in server
- [ ] Data sync between browser and server (autosave)
- [ ] Data storage format (to be parsed by the browser)
- [ ] Collaborative editing of a notebook, how to sync browsers
## Acceptance criteria
TBD
## Test procedures
TBD
## Dependencies
Depends on #25
