### ISSUE TITLE
Notebook Step controller

### ISSUE THREAD

**Issue by ezorita** [palicode/nucleotid-back#25]
## Description
Code to read, create, delete and update Notebook steps.
## Subtasks
- [ ] A notebook step must reference where the data is stored. How?
- Middlewares:
  - [ ] `createNotebookStep`
  - [ ] `getNotebookStep`
  - [ ] `updateNotebookStep`
  - [ ] `deleteNotebookStep`
- Test code:
  - [ ] `createNotebookStep`
  - [ ] `getNotebookStep`
  - [ ] `updateNotebookStep`
  - [ ] `deleteNotebookStep`
## Acceptance criteria
- [ ] Test code coverage ~100%.
- [ ] Possibility to Create, Read, Update and Delete Notebook Steps.
## Test procedures
- [ ] Test API endpoints.
## Dependencies
Depends on #21
