### ISSUE TITLE
Redis

### ISSUE THREAD

**Issue by ezorita** [palicode/nucleotid-back#4]
**TODO**:
- [ ] Add Redis server to development Docker.
- [ ] Configure express-session store -> Redis.
- [ ] Define session expiration time (normal login vs remember me?)
- [ ] Test session permanence after restarting server (are they stored in disk by Redis?).
- [ ] What session information is stored in Redis?
- [ ] Avoid, if possible, to query user info after every cookie deserialization.

**Comment by ezorita** [comment]
Not using Redis, RESTful APIs do not have sessions. Using OAUTH2 with JWT instead.
