### ISSUE TITLE
HTTPS on Dev

### ISSUE THREAD

**Issue by ezorita** [palicode/nucleotid-back#5]
**TODO**:
- [x] Generate local CA and SSL certificates to use HTTPS in development.
- [x] Add middleware to force HTTPS in all pages.
- [x] Enable and configure `https` package in Node.
